// <auto-generated />
namespace LagDaemon.InformationManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddocumententities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddocumententities));
        
        string IMigrationMetadata.Id
        {
            get { return "201702130054515_added document entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
